language: python
cache: pip
sudo: required
services:
  - docker
matrix:
  include:
  - name: "pip on Ubuntu 18.04"
    env:
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=linux
      - DVC_TEST_DISTRO=ubuntu
      - DVC_TEST_DISTRO_VERSION=18.04
      - DVC_TEST_PKG=pip
#    - name: "deb on Ubuntu 18.04"
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=linux
#        - DVC_TEST_DISTRO=ubuntu
#        - DVC_TEST_DISTRO_VERSION=18.04
#        - DVC_TEST_PKG=deb
  - name: "pip on Ubuntu 16.04"
    env:
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=linux
      - DVC_TEST_DISTRO=ubuntu
      - DVC_TEST_DISTRO_VERSION=16.04
      - DVC_TEST_PKG=pip
#    - name: "deb on Ubuntu 16.04"
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=linux
#        - DVC_TEST_DISTRO=ubuntu
#        - DVC_TEST_DISTRO_VERSION=16.04
#        - DVC_TEST_PKG=deb
  
  - name: "pip on Fedora 28"
    env:
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=linux
      - DVC_TEST_DISTRO=fedora
      - DVC_TEST_DISTRO_VERSION=28
      - DVC_TEST_PKG=pip
#    - name: "rpm on Fedora 28"
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=linux
#        - DVC_TEST_DISTRO=fedora
#        - DVC_TEST_DISTRO_VERSION=28
#        - DVC_TEST_PKG=rpm
  - name: "pip on Fedora 27"
    env:
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=linux
      - DVC_TEST_DISTRO=fedora
      - DVC_TEST_DISTRO_VERSION=27
      - DVC_TEST_PKG=pip
#    - name: "rpm on Fedora 27"
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=linux
#        - DVC_TEST_DISTRO=fedora
#        - DVC_TEST_DISTRO_VERSION=27
#        - DVC_TEST_PKG=rpm
  - name: "pip on Fedora 26"
    env:
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=linux
      - DVC_TEST_DISTRO=fedora
      - DVC_TEST_DISTRO_VERSION=26
      - DVC_TEST_PKG=pip
#    - name: "rpm on Fedora 26"
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=linux
#        - DVC_TEST_DISTRO=fedora
#        - DVC_TEST_DISTRO_VERSION=26
#        - DVC_TEST_PKG=rpm
  - name: "pip on MacOS"
    os: osx
    osx_image: xcode9.3
    language: ruby
    rvm: 2.4.0
    env:
      - PYTHON_VER=2.7.10
      - PYENV_ROOT="$HOME/.pyenv"
      - PATH="$PYENV_ROOT/bin:$PATH"
      - DVC_TEST_OS=posix
      - DVC_TEST_SYSTEM=osx
      - DVC_TEST_PKG=pip
#    - name: "pkg on MacOS"
#      os: osx
#      env:
#        - DVC_TEST_OS=posix
#        - DVC_TEST_SYSTEM=osx
#        - DVC_TEST_PKG=pkg

before_install:
  - if  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$(pyenv init -)";
      PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing --keep --verbose "$PYTHON_VER";
      pyenv shell "$PYTHON_VER";
    fi
  - pip install -r requirements.txt
    
script:
  - python run.py
